FROM ollama/ollama:0.5.7

# Serve Ollama and Pull Ollama Model
RUN bash -c "ollama serve &" && \
    sleep 5 && \
    ollama pull gemma2:2b && \
    ollama pull gemma2:9b && \
    ollama pull gemma2:27b && \
    ollama pull llama3.1:8b && \
    ollama pull llama3.2:3b