apiVersion: kubeai.org/v1
kind: Model
metadata:
  name: gemma2-9b
  namespace: default
spec:
  features: [TextGeneration]
  image: leoho0722/ollama-builtin-gemma2-9b:0.1.0
  url: ollama://gemma2:9b
  engine: OLlama
  replicas: 1
  minReplicas: 1
  targetRequests: 50
  scaleDownDelaySeconds: 30
  env:
    OLLAMA_KEEP_ALIVE: "0s"
  resourceProfile: cpu:4
