apiVersion: kubeai.org/v1
kind: Model
metadata:
  name: llama3.1-8b
  namespace: default
spec:
  features: [TextGeneration]
  image: leoho0722/ollama-builtin-llama3.1-8b:0.1.0
  url: ollama://llama3.1:8b
  engine: OLlama
  replicas: 1
  minReplicas: 1
  targetRequests: 50
  scaleDownDelaySeconds: 30
  env:
    OLLAMA_KEEP_ALIVE: "0s"
  resourceProfile: cpu:4
